import './scss/main.scss';
import './js/charts.js';
import './js/main.js';
import dasboard from './images/svg-icons/dashboard.svg';
import wallet from './images/svg-icons/wallet.svg';
import dasbopaperPlaneard from './images/svg-icons/paper-plane.svg';
import swap from './images/svg-icons/swap.svg';
import user from './images/svg-icons/user.svg';
import arrowDown from './images/svg-icons/arrow-down.svg';
import notification from './images/svg-icons/notification.svg';
import menu from './images/svg-icons/menu.svg';
import search from './images/svg-icons/search.svg';
import face from './images/face.jpg';
import Illustrations from './images/svg-icons/Illustrations.svg';
import menuDots from './images/svg-icons/menu-dots.svg';
import userAvatar from './images/user-avatar.jpg';
import userAvatar2 from './images/user-avatar2.jpg';
import arrowUpRight from './images/svg-icons/arrow-up-right.svg';
import './blocks/notifications/__info-chart-wrap/js/notifications__info-chart.js';
import './blocks/alert-frame/__dismis/js/alert-frame__dismis.js';
import './blocks/header/__notification/js/header__notification.js';
import bitcoin from './images/svg-icons/bitcoin.svg';
import ethereum from './images/svg-icons/ethereum.svg';
import litecoin from './images/svg-icons/litecoin.svg';
import './blocks/wallets/__info-chart/js/wallets__info-chart.js';
import './blocks/wallets/__elem/js/wallets__elem.js';
import './blocks/big-chart/js/big-chart.js';
import bigChartBg from './images/big-chart-bg.png';
import './blocks/trend/__chart/js/trend__chart.js';
import './blocks/history/js/history.js';
import './blocks/navigation/js/navigation.js';
import icon from './images/favicon.ico';
import icon16 from './images/favicon-16x16.png';
import icon32 from './images/favicon-32x32.png';
import icon96 from './images/favicon-96x96.png';
import icon120 from './images/favicon-120x120.png';
import icon192 from './images/favicon-192x192.png';