import './scss/main.scss';
import './js/main.js';
import dasboard from './images/svg-icons/dashboard.svg';
import wallet from './images/svg-icons/wallet.svg';
import dasbopaperPlaneard from './images/svg-icons/paper-plane.svg';
import swap from './images/svg-icons/swap.svg';
import user from './images/svg-icons/user.svg';
import arrowDown from './images/svg-icons/arrow-down.svg';
import notification from './images/svg-icons/notification.svg';
import menu from './images/svg-icons/menu.svg';
import search from './images/svg-icons/search.svg';
import face from './images/face.jpg';
import Illustrations from './images/svg-icons/Illustrations.svg';